### ISSUE TITLE
[QUESTION] Windows Support

### ISSUE THREAD

**Issue by AquilaSagitta** [xoloki/purple-irc-nomode#1]
How do I get this to work in windows?

**Comment by xoloki** [comment]
I've never built a libpurple plugin on windows.  Presumably if you can build pidgin from source, you can hijack the build and add irc-nomode.  

I can probably cross compile something on Linux for you.

**Comment by xoloki** [comment]
Please try the attached zip file, which contains irc-nomode.dll. It seemed to build okay with mingw/msys.

[irc-nomode.zip](https://github.com/xoloki/purple-irc-nomode/files/80640/irc-nomode.zip)

**Comment by xoloki** [comment]
Please try the attached zip file, which contains irc-nomode.dll.  It seemed to build okay with mingw/msys.

**Comment by xoloki** [comment]
Closing for now.  Please reopen if the dll doesn't work.
