### ISSUE TITLE
Install to ~/.purple/plugins if running "make install" as non-root?

### ISSUE THREAD

**Issue by fghaas** [xoloki/purple-irc-nomode#2]
This is exceedingly useful, thanks a ton for writing this!

The build chain currently seems to install to the global plugin directory (`/usr/lib/purple-2/`) unconditionally, and thus `make install` is required to run as root. Purple does support per-user plugins in `~/.purple/plugins/`.

Would you consider changing the build chain slightly such that if `make install` is invoked as non-root, you install to the per-user plugin directory instead? Or maybe add a configure flag to that effect?

**Comment by xoloki** [comment]
I added a configure option: --enable-per-user-plugins
Please try it out and let me know if it works for you.

**Comment by fghaas** [comment]
Works like a charm, thanks! Installs with 0755 permission bits (0644 would be sufficient), but does exactly what it says on the tin. Thanks again!

**Comment by xoloki** [comment]
Excellent, closing.
